### ISSUE TITLE
PollForChanges should delay checking if consul is not available

### ISSUE THREAD

**Issue by barbarosalp** [wintoncode/Winton.Extensions.Configuration.Consul#70]
When Consul is not available `OnWatchException` is triggered constantly. Because there is no delay being applied in the catch.

```
while (!cancellationToken.IsCancellationRequested)
            {
                try
                {
                    if (await HasValueChanged(key, cancellationToken).ConfigureAwait(false))
                    {
                        ConfigurationReloadToken previousToken = Interlocked.Exchange(
                            ref _reloadToken,
                            new ConfigurationReloadToken());
                        previousToken.OnReload();
                        return;
                    }
                }
                catch (Exception exception)
                {
                    var exceptionContext = new ConsulWatchExceptionContext(cancellationToken, exception);
                    onException?.Invoke(exceptionContext);
                }
            }
```
This is the exception being thrown:
```
  System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Consul.GetRequest`1.Execute(CancellationToken ct)
   at Winton.Extensions.Configuration.Consul.ConsulConfigurationClient.GetKvPairs(String key, CancellationToken cancellationToken, QueryOptions queryOptions)
   at Winton.Extensions.Configuration.Consul.ConsulConfigurationClient.HasValueChanged(String key, CancellationToken cancellationToken)
   at Winton.Extensions.Configuration.Consul.ConsulConfigurationClient.PollForChanges(String key, Action`1 onException, CancellationToken cancellationToken)
```

**Comment by Choc13** [comment]
Hi @barbarosalp,

Thanks for opening this. It certainly seems like something that we should improve. I'll take a look at your PR now.
